---
categories:
  - title: 🚀 Features
    label: enhancement
  - title: 🐛 Bug Fixes
    label: bug
  - title: 📖 Documentation
    label: documentation
exclude-labels:
  - 'skip-changelog'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## What's Changed: 
  $CHANGES 
